force-app/main/default/objects/Additional_Subject_Settings__mdt/Additional_Subject_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Additional Subject Setting</label>
    <pluralLabel>Additional Subject Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Additional_Subject_Settings__mdt/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AdditionalSubjectSettingsUtility.cls
public with sharing class AdditionalSubjectSettingsUtility {
    public static Decimal GetAmountBySubject(String sbjctName) {
        List<Additional_Subject_Settings__mdt> getSubjectList =[SELECT Id,Amount__c, Label 
                                                                FROM Additional_Subject_Settings__mdt 
                                                                WHERE Label=:sbjctName];
        if (getSubjectList.size() != 0) {
            return getSubjectList[0].Amount__c;
            
        }else {
            return null;
        }

    }
}