force-app/main/default/objects/Parent__c/Parent__c.object-meta.xml
<CustomObject>
    <label>Parent</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Parent ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ValidationRuleConfig__mdt/ValidationRuleConfig__mdt.object-meta.xml
<CustomObject>
    <label>ValidationRuleConfig</label>
    <pluralLabel>ValidationRuleConfig</pluralLabel>
</CustomObject>

force-app/main/default/objects/ValidationRuleConfig__mdt/fields/All__c.field-meta.xml
<CustomField>
    <fullName>All__c</fullName>
    <defaultValue>false</defaultValue>
    <label>All</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ValidationRuleConfig__mdt/fields/Child__c.field-meta.xml
<CustomField>
    <fullName>Child__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Child</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ValidationRuleConfig__mdt/fields/GardenRelationship__c.field-meta.xml
<CustomField>
    <fullName>GardenRelationship__c</fullName>
    <defaultValue>false</defaultValue>
    <label>GardenRelationship</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ValidationRuleConfig__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ValidationRuleConfig__mdt/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Package</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ValidationRuleConfig__mdt/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Parent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ValidationRuleConfig__mdt/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ValidationRuleConfig__mdt/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ValidationRuleConfigUtility.cls
public with sharing class ValidationRuleConfigUtility {
    
    public static ValidationRuleConfig__mdt	getVrConfig() {

      List<ValidationRuleConfig__mdt> VRConfig = [SELECT Id, All__c, GardenRelationship__c, Order__c,	Parent__c, Child__c, Plan__c, Package__c, Payment_Status__c	 FROM ValidationRuleConfig__mdt ];

          if (VRConfig.size() != 0){
            return VRConfig[0];
          }else {
            return null;
          }
    }
          
}