force-app/main/default/objects/Parent__c/Parent__c.object-meta.xml
<CustomObject>
    <label>Parent</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Parent ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parent__c/fields/Father_Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Father_Birthdate__c</fullName>
    <label>Father Birthdate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Parent__c/fields/Father_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Father_Full_Name__c</fullName>
    <label>Father Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parent__c/fields/Father_Phone__c.field-meta.xml
<CustomField>
    <fullName>Father_Phone__c</fullName>
    <label>Father Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Parent__c/fields/Guardian_BirthDate__c.field-meta.xml
<CustomField>
    <fullName>Guardian_BirthDate__c</fullName>
    <label>Guardian BirthDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Parent__c/fields/Guardian_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Guardian_Mobile__c</fullName>
    <label>Guardian Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Parent__c/fields/Guardian_Phone__c.field-meta.xml
<CustomField>
    <fullName>Guardian_Phone__c</fullName>
    <label>Guardian Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Parent__c/fields/Guardian_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Guardian_Relationship__c</fullName>
    <label>Guardian Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parent__c/fields/Mother_Phone__c.field-meta.xml
<CustomField>
    <fullName>Mother_Phone__c</fullName>
    <label>Mother Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/ParentTriggerHandler.cls
public  class ParentTriggerHandler {
    public static void UpdateParent(List<Parent__c> parents) {
        for (Parent__c prnt : parents) {
            if (prnt.Guardian_Relationship__c=='Father') {
                 prnt.Guardian_Name__c=prnt.Father_Full_Name__c;
                 prnt.Guardian_Mobile__c=prnt.Father_Mobile__c;
                 prnt.Guardian_BirthDate__c=prnt.Father_Birthdate__c;
                prnt.Guardian_Phone__c= prnt.Father_Phone__c;
                 prnt.Guardian_Email__c=prnt.Father_Email__c;
                
            }else if (prnt.Guardian_Relationship__c=='Mother') {
                prnt.Guardian_Name__c=prnt.Mother_Full_Name__c;
                 prnt.Guardian_Mobile__c=prnt.Mother_Mobile__c;
                 prnt.Guardian_BirthDate__c=prnt.Mother_Birthdate__c;
                prnt.Guardian_Phone__c= prnt.Mother_Phone__c;
                 prnt.Guardian_Email__c=prnt.Mother_Email__c;
            }

    }
}


}