force-app/main/default/objects/Parent__c/Parent__c.object-meta.xml
<CustomObject>
    <label>Parent</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Parent ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>ID-{0000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Child__c.field-meta.xml
<CustomField>
    <fullName>Child__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Child</label>
    <referenceTo>Children__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Month_Paid__c.field-meta.xml
<CustomField>
    <fullName>Month_Paid__c</fullName>
    <label>Month Paid</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Service Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Child__c.field-meta.xml
<CustomField>
    <fullName>Child__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Child</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Children__c.Parent__c</field>
            <operation>equals</operation>
            <valueField>$Source.Parent__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Children__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <label>Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ServiceTriggerHandler.cls
public with sharing class ServiceTriggerHandler {

   

    public static void insertServiceTriggerHandler(List<Service__c> serviceList) { 
        List<String> successLogs = new List<String>();
        List<String> errorLogs = new List<String>();

    try {
        List<Payment__c> paymnts= new  List<Payment__c>();
    
        for (Service__c newService : serviceList) {
        
            if(newService.Plan__c=='Monthly'){
                integer numbr =PaymentInstallmentsSettingUtility.NumberOfInstallments('Monthly');
                string strtMonth = PaymentInstallmentsSettingUtility.paymentsStartsOn('Monthly');
                integer strtMonthIntgr =DateUtility.getMonthInNumber(strtMonth);
                integer endMonth = strtMonthIntgr+numbr;
                for (Integer i = strtMonthIntgr; i < endMonth; i++) {
                    Payment__c paymnt= new Payment__c();
                    paymnt.Parent__c= newService.Parent__c;
                    paymnt.Child__c=newService.Child__c;
                    paymnt.Service__c =newService.Id;
                    paymnt.Month_Paid__c=Datetime.newInstance(2024, i, 1).format('MMMM');
                    paymnt.Payment_Date__c= Date.newInstance(2024, i, 1);
                    paymnt.Total_Amount__c = PaymentUtility.calculateTotalAmount(paymnt, newService);
                    paymnt.Plan__c= 'Monthly';
                   paymnts.add(paymnt);
                }
            } else if (newService.Plan__c=='Yearly') {
                string strtMonth = PaymentInstallmentsSettingUtility.paymentsStartsOn('Yearly');
                Decimal dscnt = PaymentInstallmentsSettingUtility.discount('Yearly');
                Payment__c paymnt= new Payment__c();
                paymnt.Parent__c= newService.Parent__c;
                paymnt.Child__c=newService.Child__c;
                paymnt.Service__c=newService.Id;
                paymnt.Month_Paid__c=strtMonth;
                paymnt.Total_Amount__c = PaymentUtility.calculateTotalAmount(paymnt, newService);
                paymnt.Plan__c= 'Yearly';
                paymnts.add(paymnt);
            }
           insert paymnts; 
        }
          APILogUtility.SuccessLog('ServiceTriggerHandler', successLogs);
        
     
        } catch (Exception e){
            errorLogs.add(String.valueOf(e.getCause()));
            errorLogs.add(e.getMessage());
            errorLogs.add(string.valueOf(e.getLineNumber()));
            errorLogs.add(string.valueOf(e.getNumDml()));
            errorLogs.add(e.getStackTraceString());
            APILogUtility.ErrorLog('ServiceTriggerHandler', errorLogs);

        }

    }
}