force-app/main/default/objects/API_Log__c/API_Log__c.object-meta.xml
<CustomObject>
    <label>API Log</label>
    <nameField>
        <displayFormat>ID-{00000000}</displayFormat>
        <label>API Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Log__c/fields/Log_Message__c.field-meta.xml
<CustomField>
    <fullName>Log_Message__c</fullName>
    <label>Log Message</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/APILogUtility.cls
public with sharing class APILogUtility {
    public static void ErrorLog( string APIName, List<string> logMessage ) {
        API_Log__c log = new API_Log__c();
        log.API_Name__c = APIName;
        log.Log_Message__c= String.join(logMessage,';' );
        log.Is_Error__c= true;
         insert log;

    }
    public static void SuccessLog(string APIName, List<string> logMessage){
        API_Log__c log =new API_Log__c();
        log.API_Name__c= APIName;
        log.Log_Message__c =  String.join(logMessage,';' );
        log.Is_Error__c = False;
        insert log;
    }
}