force-app/main/default/objects/API_Log__c/API_Log__c.object-meta.xml
<CustomObject>
    <label>API Log</label>
    <nameField>
        <displayFormat>ID-{00000000}</displayFormat>
        <label>API Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Children__c/Children__c.object-meta.xml
<CustomObject>
    <label>Children</label>
    <nameField>
        <label>Child Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Children__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Expense ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue</label>
    <referenceTo>Revenue__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inbound_Record__c/Inbound_Record__c.object-meta.xml
<CustomObject>
    <label>Inbound Record</label>
    <nameField>
        <displayFormat>ID-{00000000}</displayFormat>
        <label>IR ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Income__c/Income__c.object-meta.xml
<CustomObject>
    <label>Income</label>
    <nameField>
        <displayFormat>ID-{000000}</displayFormat>
        <label>Income ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incomes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Income__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Incomes</relationshipLabel>
    <relationshipName>Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Income__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue</label>
    <referenceTo>Revenue__c</referenceTo>
    <relationshipLabel>Incomes</relationshipLabel>
    <relationshipName>Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parent__c/Parent__c.object-meta.xml
<CustomObject>
    <label>Parent</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Parent ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>ID-{0000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue__c/Revenue__c.object-meta.xml
<CustomObject>
    <label>Revenue</label>
    <nameField>
        <displayFormat>ID-{000000}</displayFormat>
        <label>Revenue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Service Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ORGUtility.cls
public  class ORGUtility {
    public static void  DeletePayments() {
        List<Payment__c> paymentsToDelete = [SELECT Id FROM Payment__c];
        delete paymentsToDelete;
    }
    public static void  DeleteServices() {
        List<Service__c> serviceToDelete = [SELECT Id FROM Service__c];
        delete serviceToDelete;
    }
    public static void  DeleteChildren() {
        List<Children__c> childrenToDelete = [SELECT Id FROM Children__c];
        delete childrenToDelete;
    }
    public static void  DeleteParents() {
        List<Parent__c> parentToDelete = [SELECT Id FROM Parent__c];
        delete parentToDelete;
    }
    public static void  DeleteIncomes() {
        List<Income__c>incomesToDelete = [SELECT Id FROM Income__c];
        delete incomesToDelete;
    }
    public static void  DeleteExpenses() {
        List<Expense__c> expensesToDelete = [SELECT Id FROM Expense__c];
        delete expensesToDelete;
    }
    public static void  DeleteRevenues() {
        List<Revenue__c> revenuesToDelete = [SELECT Id FROM Revenue__c];
        delete revenuesToDelete;
    }
    public static void  DeleteAPILogs() {
        List<API_Log__c> apilogsToDelete = [SELECT Id FROM API_Log__c];
        delete apilogsToDelete;
    }
    public static void  DeleteInboundRecords() {
        List<Inbound_Record__c> inboundRecordsToDelete = [SELECT Id FROM Inbound_Record__c];
        delete inboundRecordsToDelete;
    }
    public static void  DeleteCases() {
        List<Case> casesToDelete = [SELECT Id FROM Case];
        delete casesToDelete;
    }
    public static void  DeleteAllRecords() {
        DeleteAllRecords();
    }
}