force-app/main/default/objects/Income__c/Income__c.object-meta.xml
<CustomObject>
    <label>Income</label>
    <nameField>
        <displayFormat>ID-{000000}</displayFormat>
        <label>Income ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incomes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Income__c/fields/Income_Date__c.field-meta.xml
<CustomField>
    <fullName>Income_Date__c</fullName>
    <label>Income Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Income__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Incomes</relationshipLabel>
    <relationshipName>Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>ID-{0000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Refund Pending</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Service Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PaymentTriggerHandler.cls
public  class PaymentTriggerHandler {


    public static void CreateNewIncome(List<Payment__c> paymentList){
        
        List<String> successLogs = new List<String>();
        List<String> errorLogs = new List<String>();
        
        try {
            List<Income__c> newIncomes = new List<Income__c>();
        
        for(Payment__c payment : paymentList){
            
            if(payment.Payment_Status__c =='Paid'){
                
                Income__c newIncome = new Income__c();
                newIncome.Amount__c = payment.Paid_Amount__c;
                newIncome.Income_Date__c = payment.Payment_Date__c;
                newIncome.Payment__c= payment.Id;
                
                newIncomes.add(newIncome);

            }

        }
        insert newIncomes;
            
            successLogs.add(newIncomes.size() + ' new incomes created.');
            
            successLogs.add('New Incomes created successfully.');
            
            APILogUtility.SuccessLog('PaymentTriggerHandler', successLogs);
        }
        
        catch(Exception e){
            errorLogs.add('New Incomes could not be created.');
            APILogUtility.ErrorLog('PaymentTriggerHandler',errorLogs);
        }
    }
    public static void updateTotalPaidAmount(List<Payment__c> paymentList){

        List<Service__c> serviceList = new   List<Service__c>();

        for (Payment__c payment : paymentList) {
           Service__c relatedService = ServiceUtility.getServiceById(payment.Service__c);
           relatedService.Total_Amount__c =+ payment.Paid_Amount__c;  
           serviceList.add(relatedService);    
        }

    
        update serviceList;
 
     }
     

}