force-app/main/default/objects/Service_Amount_Settings__mdt/Service_Amount_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Service Amount Setting</label>
    <pluralLabel>Service Amount Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Service_Amount_Settings__mdt/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Combo Package</fullName>
                <default>true</default>
                <label>Combo Package</label>
            </value>
            <value>
                <fullName>Core Subjects</fullName>
            </value>
            <value>
                <fullName>Single Subject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ServiceAmountSettingUtility.cls
public class ServiceAmountSettingUtility {
    public static decimal  GetServiceAmountByPackType(string srvpackage) {
        
            List<Service_Amount_Settings__mdt> srvcList = [SELECT Id, Amount__c,Package__c 
            FROM Service_Amount_Settings__mdt 
            WHERE Package__c =:srvpackage ];

                if (srvcList.isEmpty()) {
                    
                return srvcList[0].Amount__c;

                }else {

                return 0.00;

                }

                
            }
       
    }