force-app/main/default/objects/Payment_Installments_Setting__mdt/Payment_Installments_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Payment Installments Setting</label>
    <pluralLabel>Payment Installments Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Payment_Installments_Setting__mdt/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Installments_Setting__mdt/fields/Number_of_Installments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Installments__c</fullName>
    <label>Number of Installments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Installments_Setting__mdt/fields/Payments_Starts_on__c.field-meta.xml
<CustomField>
    <fullName>Payments_Starts_on__c</fullName>
    <label>Payments Starts on</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
                <default>true</default>
                <label>January</label>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Installments_Setting__mdt/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <label>Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentInstallmentsSettingUtility.cls
public class PaymentInstallmentsSettingUtility {
    public static integer NumberOfInstallments(String plan) {
        Payment_Installments_Setting__mdt pIs = [SELECT Discount__c, Number_of_Installments__c, Payments_Starts_on__c, 	Plan__c
                                                 FROM Payment_Installments_Setting__mdt pIs WHERE Plan__c= :plan ];

        return integer.valueOf(pIs.Number_of_Installments__c);

    }
    public static integer discount(String plan) {
        Payment_Installments_Setting__mdt pIs = [SELECT Discount__c, Number_of_Installments__c, Payments_Starts_on__c, 	Plan__c
                                                 FROM Payment_Installments_Setting__mdt pIs WHERE Plan__c= :plan ];

        return integer.valueOf(pIs.Discount__c);

    }

    public static string paymentsStartsOn(String plan) {
        Payment_Installments_Setting__mdt pIs = [SELECT Discount__c, Number_of_Installments__c, Payments_Starts_on__c, 	Plan__c
                                             FROM Payment_Installments_Setting__mdt pIs WHERE Plan__c= :plan ];

    return pIs.Payments_Starts_on__c;

}
}