force-app/main/default/objects/Children__c/Children__c.object-meta.xml
<CustomObject>
    <label>Children</label>
    <nameField>
        <label>Child Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Children__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First Child</fullName>
            </value>
            <value>
                <fullName>Second Child</fullName>
            </value>
            <value>
                <fullName>Third Child</fullName>
            </value>
            <value>
                <fullName>Fourth Child</fullName>
            </value>
            <value>
                <fullName>Fifth Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChildUtility.cls
// public with sharing class ChildUtility {
//     public static Children__c getChild(Id chldId ) {
//         List<Children__c> childList = [SELECT Id,Order__c FROM Children__c WHERE Id=: chldId];
//         if(!childList.isEmpty()){
//             return childList[0];
//         }else {
//             return null;
//         }

//     }
// }
public with sharing class ChildUtility {
    public static Children__c getChild(Id chldId) {
       
            List<Children__c> childList = [SELECT Id, Order__c FROM Children__c WHERE Id = :chldId];
            if (!childList.isEmpty()) {
                return childList[0];
            } else {
                return null;
            }
    }
}