force-app/main/default/objects/Children__c/Children__c.object-meta.xml
<CustomObject>
    <label>Children</label>
    <nameField>
        <label>Child Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Children__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parent__c/Parent__c.object-meta.xml
<CustomObject>
    <label>Parent</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Parent ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parent__c/fields/Father_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Father_Full_Name__c</fullName>
    <label>Father Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Service Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <label>Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestUtilityTEST.cls
@isTest
public class TestUtilityTEST {
    
    @isTest
    static void TestA(){
        
        TestUtility.TestRecords();
        
    }
    
    
    @isTest
    static void TestB(){
        
        TestUtility.NTestRecords(10);
        
    }
    
    @isTest
    static void TestC(){
        
        Test.StartTest();
        TestUtility.NewParent1('Aysun Hanim','Mother');
        Test.StopTest();
        
        Parent__c AysunParent = [SELECT id, Father_Full_Name__c FROM Parent__c LIMIT 1];
        
        System.assertEquals('Aysun Hanim', AysunParent.Father_Full_Name__c);
        
        
        
    }
    
    @isTest
    static void TestD(){
        
        TestUtility.genarateRandomParentFromList();
        
    }
    
    @isTest
    static void TestE(){
        
        Parent__c newParent = TestUtility.NewParent();
        Children__c newChild = TestUtility.NewChild(newParent.Id);
        Service__c newService = TestUtility.NewService(newParent.Id, newChild.id );
        
        newService.Plan__c ='Yearly';
        
        update newService;
        
        
        TestUtility.NewPayments(newParent.Id, newChild.Id, newService.Id);
        
        
    }
    
}