force-app/main/default/objects/Children__c/Children__c.object-meta.xml
<CustomObject>
    <label>Children</label>
    <nameField>
        <label>Child Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Children__c/fields/Grade_Level__c.field-meta.xml
<CustomField>
    <fullName>Grade_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grade Level</label>
    <referenceTo>Grade_Level__c</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grade_Level__c/Grade_Level__c.object-meta.xml
<CustomObject>
    <label>Grade Level</label>
    <nameField>
        <label>Grade Level</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grade Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ChildrenTriggerHandler.cls
public with sharing class ChildrenTriggerHandler {
     public static void updateNumberOfChildrenOnInsert(List<Children__c> childList){
        Set<Id> gradeLevelIds = new Set<Id>();

        for (Children__c child : childList) {
            gradeLevelIds.add(child.Grade_Level__c);       
        }

        List<Grade_Level__c> gradeLevelList =[SELECT Id, Number_Of_Children__c, (SELECT Id FROM Children__r) 
                                              FROM Grade_Level__c 
                                              WHERE  Id IN :gradeLevelIds];

        for (Grade_Level__c grade : gradeLevelList) {
            grade.Number_of_Children__c = grade.Children__r.size();
        }
        update gradeLevelList;
 
     }
     public static void updateNumberOfChildrenOnUpdate(List<Children__c> oldChildren, List<Children__c> newChildren){
        
        Set<Id> gradeLevelIDs = new Set<Id>();
        
        for(Children__c oldChild : oldChildren){
            for(Children__c newChild : newChildren){
                if(oldChild.Grade_Level__c != newChild.Grade_Level__c){
                    gradeLevelIDs.add(oldChild.Grade_Level__c);
                    gradeLevelIDs.add(newChild.Grade_Level__c);
                }
            }
        }
        
        List<Grade_Level__c> gradeLevelList = [SELECT Id, Number_Of_Children__c, (SELECT Id FROM Children__r) 
                                                FROM Grade_Level__c WHERE Id IN :gradeLevelIDs];
        
        for(Grade_Level__c grade : gradeLevelList){
            grade.Number_of_Children__c = grade.Children__r.size();
        }
        update gradeLevelList;
    }
}