force-app/main/default/objects/Children__c/Children__c.object-meta.xml
<CustomObject>
    <label>Children</label>
    <nameField>
        <label>Child Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Children__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First Child</fullName>
            </value>
            <value>
                <fullName>Second Child</fullName>
            </value>
            <value>
                <fullName>Third Child</fullName>
            </value>
            <value>
                <fullName>Fourth Child</fullName>
            </value>
            <value>
                <fullName>Fifth Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>ID-{0000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Child__c.field-meta.xml
<CustomField>
    <fullName>Child__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Child</label>
    <referenceTo>Children__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Late_Fee__c.field-meta.xml
<CustomField>
    <fullName>Late_Fee__c</fullName>
    <label>Late Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Fee__c.field-meta.xml
<CustomField>
    <fullName>Payment_Fee__c</fullName>
    <label>Payment Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Paypal</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Bank Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Transaction_ID__c</fullName>
    <label>Transaction ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Service Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Additional_Subjects__c.field-meta.xml
<CustomField>
    <fullName>Additional_Subjects__c</fullName>
    <label>Additional Subjects</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Turkish</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Child__c.field-meta.xml
<CustomField>
    <fullName>Child__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Child</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Children__c.Parent__c</field>
            <operation>equals</operation>
            <valueField>$Source.Parent__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Children__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single Subject</fullName>
            </value>
            <value>
                <fullName>Core Subjects</fullName>
            </value>
            <value>
                <fullName>Combo Package</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentUtility.cls
public with sharing class PaymentUtility {



    public static Decimal calculateTotalAmount(Payment__c payment, Service__c service) {

        Decimal srvcAmount = ServiceAmountSettingUtility.GetServiceAmountByPackType(service.Package__c);
 
        Decimal addSubFee = AdditionalSubjectSettingsUtility.GetAmountBySubject(service.Additional_Subjects__c);
      
        Children__c paymntOwner = ChildUtility.getChild(service.Child__c);
       
        Decimal chldDiscnt = ChildDiscountConfigsUtility.CalculateChildDiscount(paymntOwner.Order__c);
       
        Decimal TotalPayment = srvcAmount + addSubFee;
         
        Decimal DiscountedAmount = TotalPayment - TotalPayment * chldDiscnt /100;
      

       return DiscountedAmount;

}
public static void FinalPayment(List<Payment__c> paymentList) {

    for (Payment__c payment : paymentList) {
        Decimal PaymentPercentage = PaymentMethodSettingUtility.GetServiceChargeByPaymentMethod(Payment.Payment_Method__c);
        Decimal PaymentFee = payment.Total_Amount__c * PaymentPercentage / 100;
        Decimal PaymentTaxPercentage = TaxSettingUtility.DefaultTax();
        Decimal TaxAmount = payment.Total_Amount__c * PaymentTaxPercentage / 100;

        Decimal LateFee = 0.00;

        if (payment.Due_Date__c < payment.Payment_Date__c) {
            LateFee = payment.Total_Amount__c * 0.1;
        }

        Decimal PaidAmount = payment.Total_Amount__c + TaxAmount + LateFee + PaymentFee;

        //********** Assignment *******//
        payment.Tax_Amount__c = TaxAmount;
        payment.Late_Fee__c = LateFee;
        payment.Payment_Fee__c = PaymentFee;
        payment.Paid_Amount__c = PaidAmount;

        if(String.isBlank(payment.Transaction_ID__c)){
                
            String TransactionId = generateTransactionID();
            
            Boolean status = transactionIdIsUnique(TransactionId);
            
            if(status){
                payment.Transaction_ID__c =TransactionId;
            }
            else {
                TransactionId = generateTransactionID();
                payment.Transaction_ID__c =TransactionId;
            }
            
        }
        
    }
    }

public static String generateTransactionID(){
        
    String charSet = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
    
    String TransactionID =''; 
    
    for(Integer i=0; i<16; i++){ 
      
        Integer randomIndex = Math.mod(Math.round(Math.random() * 250), charSet.length());
        
        TransactionID += charSet.subString(randomIndex, randomIndex+1);        
    }
    return TransactionID;
    
}

public static Boolean transactionIdIsUnique(String TId){
    
    List<Payment__c> TIDList = [SELECT Transaction_ID__c FROM Payment__c WHERE Transaction_ID__c =: TId];
    
    if(TIDList.size() != 0){
        return false;
    }
    else {
        return true;
    }
    
}



}