force-app/main/default/objects/Children__c/Children__c.object-meta.xml
<CustomObject>
    <label>Children</label>
    <nameField>
        <label>Child Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Children__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First Child</fullName>
            </value>
            <value>
                <fullName>Second Child</fullName>
            </value>
            <value>
                <fullName>Third Child</fullName>
            </value>
            <value>
                <fullName>Fourth Child</fullName>
            </value>
            <value>
                <fullName>Fifth Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Children__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parent__c/Parent__c.object-meta.xml
<CustomObject>
    <label>Parent</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Parent ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parent__c/fields/Father_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Father_Full_Name__c</fullName>
    <label>Father Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parent__c/fields/Guardian_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Guardian_Relationship__c</fullName>
    <label>Guardian Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>ID-{0000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Child__c.field-meta.xml
<CustomField>
    <fullName>Child__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Child</label>
    <referenceTo>Children__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Paypal</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Bank Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Refund Pending</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Service Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Child__c.field-meta.xml
<CustomField>
    <fullName>Child__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Child</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Children__c.Parent__c</field>
            <operation>equals</operation>
            <valueField>$Source.Parent__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Children__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single Subject</fullName>
            </value>
            <value>
                <fullName>Core Subjects</fullName>
            </value>
            <value>
                <fullName>Combo Package</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <label>Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ValidationRuleConfig__mdt/ValidationRuleConfig__mdt.object-meta.xml
<CustomObject>
    <label>ValidationRuleConfig</label>
    <pluralLabel>ValidationRuleConfig</pluralLabel>
</CustomObject>

force-app/main/default/objects/ValidationRuleConfig__mdt/fields/All__c.field-meta.xml
<CustomField>
    <fullName>All__c</fullName>
    <defaultValue>false</defaultValue>
    <label>All</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ValidationRuleConfig__mdt/fields/Child__c.field-meta.xml
<CustomField>
    <fullName>Child__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Child</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ValidationRuleConfig__mdt/fields/GardenRelationship__c.field-meta.xml
<CustomField>
    <fullName>GardenRelationship__c</fullName>
    <defaultValue>false</defaultValue>
    <label>GardenRelationship</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ValidationRuleConfig__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ValidationRuleConfig__mdt/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Package</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ValidationRuleConfig__mdt/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Parent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ValidationRuleConfig__mdt/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ValidationRuleConfig__mdt/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CustomValidationRules.cls
public with sharing class CustomValidationRules {
   public static ValidationRuleConfig__mdt VrConfig =ValidationRuleConfigUtility.getVrConfig(); //this is class variable, static dedik cunku static methodlarda kullaniyoruz, public dedik ki ulasabilsin

    public static void serviceValidationRule(List<Service__c> srvList) {
        for (Service__c srvce : srvList) {

            // if (VrConfig.GardenRelationship__c) { // bu kodda sadece GardenRelationship__c secilmisse calisacak
               
   
            if(srvce.Parent__c == null&& VrConfig.Parent__c){
                srvce.Parent__c.addError('Parent must be selected');
            }
            if(srvce.Child__c == null&& VrConfig.Child__c){
                srvce.Child__c.addError('Child must be selected');
            }
            if(String.isBlank(srvce.Plan__c)&& VrConfig.Plan__c){
                srvce.Plan__c.addError('Plan must be selected');
            }
            if(String.isBlank(srvce.Package__c)&& VrConfig.Package__c){
                srvce.Plan__c.addError('Plan must be selected');
            }
            
        }

    }
    // //Normal Validation
// public static void validateField(List<Parent__c> parentList){
//     for (Parent__c parent : parentList) {
//         if(string.isBlank(parent.Guardian_Relationship__c)){
//           parent.addError('Guardian Relationship can not be blank'); //error  displays in  buttom of page
//           parent.Father_Full_Name__c.addError('Guardian Relationship can not be blank'); //error  displays in buttom

//         }
//    }
// }
    public static void validateField(List<Parent__c> parentList){
        for (Parent__c parent : parentList) {
            if(string.isBlank(parent.Guardian_Relationship__c)){

               // if (VrConfig.GardenRelationship__c) { // bu kodda sadece GardenRelationship__c secilmisse calisacak
               if (VrConfig.GardenRelationship__c || VrConfig.All__c){ // bu kod herhangi biri isaretliyse calisacak
              parent.addError('Guardian Relationship can not be blank'); //error  displays in  buttom of page
              parent.Father_Full_Name__c.addError('Guardian Relationship can not be blank'); //error  displays in buttom
    
            }
       }
       }
    }
    public static void validateField(List<Children__c> childs) {
        for (Children__c child : childs) {
            if (String.isBlank(child.Order__c)) {
                ValidationRuleConfig__mdt VrConfig =ValidationRuleConfigUtility.getVrConfig();
                if (VrConfig.Order__c || VrConfig.All__c){ // bu kod herhangi biri isaretliyse calisacak
                
            
                    child.Order__c.addError('Order can not be blank'); //error  displays in buttom
          
                  }
                
            }
            
        }

    }
    public static void validateField(List<Payment__c> payments) {
        for (Payment__c pymnt: payments) {
            if (String.isBlank(pymnt.Payment_Method__c) && pymnt.Payment_Status__c =='Paid') {
                ValidationRuleConfig__mdt VrConfig =ValidationRuleConfigUtility.getVrConfig();
                if (VrConfig.Payment_Status__c|| VrConfig.All__c){ // bu kod herhangi biri isaretliyse calisacak
                
            
                    pymnt.Payment_Method__c.addError('You must select Payment Method first'); //error  displays in buttom
          
                  }
                
            }
            
        }

    }
}