force-app/main/default/objects/Children__c/Children__c.object-meta.xml
<CustomObject>
    <label>Children</label>
    <nameField>
        <label>Child Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Children__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Expense ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Income__c/Income__c.object-meta.xml
<CustomObject>
    <label>Income</label>
    <nameField>
        <displayFormat>ID-{000000}</displayFormat>
        <label>Income ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incomes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Income__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Incomes</relationshipLabel>
    <relationshipName>Incomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parent__c/Parent__c.object-meta.xml
<CustomObject>
    <label>Parent</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Parent ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>ID-{0000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Service Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SandBoxUtility.cls
public with sharing class SandBoxUtility {
    public static void CleanOrg1() {

        delete [SELECT Id FROM Parent__c];
        delete [SELECT Id FROM Children__c];
        delete [SELECT Id FROM Service__c];
        delete [SELECT Id FROM Payment__c];
        delete [SELECT Id FROM Income__c];
        delete [SELECT Id FROM Expense__c];

    }
    public static void CleanOrg2() {

        delete [SELECT Id FROM Parent__c LIMIT 1000];
        delete [SELECT Id FROM Children__c LIMIT 1000];
        delete [SELECT Id FROM Service__c LIMIT 1000];
        delete [SELECT Id FROM Payment__c LIMIT 1000];
        delete [SELECT Id FROM Income__c LIMIT 1000];
        delete [SELECT Id FROM Expense__c LIMIT 1000];

    }
        public static void CleanOrg3() {

        List<Parent__c> pr =  [SELECT Id FROM Parent__c];
        List<Children__c> cl =  [SELECT Id FROM Children__c];
        List<Service__c> sr =  [SELECT Id FROM Service__c];
        List<Payment__c> py =  [SELECT Id FROM Payment__c];
        List<Income__c> inc =  [SELECT Id FROM Income__c];
        List<Expense__c> ex =  [SELECT Id FROM Expense__c];

        if (pr.size() >0) {
            delete pr;
        }
        if (cl.size() >0) {
            delete cl;
        }
        if (sr.size() >0) {
            delete sr;
        }
        if (py.size() >0) {
            delete py;
        }
        if (inc.size() >0) {
            delete inc;
        }
        if(ex.size() >0) {
            delete ex;
        }

    }
    public static void CleanOrg4() {

        List<SObject> pr =  [SELECT Id FROM Parent__c WHERE CreatedDate < LAST_N_DAYS:3];
        List<SObject> cl =  [SELECT Id FROM Children__c WHERE CreatedDate < LAST_N_DAYS:3];
        List<SObject> sr =  [SELECT Id FROM Service__c WHERE CreatedDate < LAST_N_DAYS:3];
        List<SObject> py =  [SELECT Id FROM Payment__c WHERE CreatedDate < LAST_N_DAYS:3];
        List<SObject> inc =  [SELECT Id FROM Income__c WHERE CreatedDate < LAST_N_DAYS:3];
        List<SObject> ex =  [SELECT Id FROM Expense__c WHERE CreatedDate < LAST_N_DAYS:3];

        List<SObject> allRecords = new  List<SObject>();
        allRecords.addAll(pr);
        allRecords.addAll(cl);
        allRecords.addAll(sr);
        allRecords.addAll(py);
        allRecords.addAll(inc);
        allRecords.addAll(ex);

        if (allRecords.size() >0) {
            delete allRecords;
            
        }
}
}