force-app/main/default/objects/Payment_Method_Setting__mdt/Payment_Method_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Payment Method Setting</label>
    <pluralLabel>Payment Method Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Payment_Method_Setting__mdt/fields/Service_Charges__c.field-meta.xml
<CustomField>
    <fullName>Service_Charges__c</fullName>
    <label>Service Charges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/PaymentMethodSettingUtility.cls
public with sharing class PaymentMethodSettingUtility {
    public static Decimal GetServiceChargeByPaymentMethod(String method) {
        List<Payment_Method_Setting__mdt> paymentMethodList =[SELECT Id, Payment_Method__c, Service_Charges__c 
                                                              FROM Payment_Method_Setting__mdt 
                                                              WHERE Payment_Method__c =:method ];
          if (!paymentMethodList.isEmpty()) {
            return paymentMethodList.get(0).Service_Charges__c;
            
          }
          else {
            return 0.00;
          }                                                  
}
}